
/* File generated by gen_cfile.py. Should not be modified. */

#include "masterNormal.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
INTEGER32 SlaveSysTick = 0x0;		/* Mapped at index 0x2000, subindex 0x00 */
UNS8 g_nRfu8 = 0x0;		/* Mapped at index 0x2001, subindex 0x00 */
UNS16 g_nRfu16 = 0x0;		/* Mapped at index 0x2002, subindex 0x00 */
UNS32 g_nRfu32 = 0x0;		/* Mapped at index 0x2003, subindex 0x00 */
UNS64 g_nRfu64 = 0x0;		/* Mapped at index 0x2004, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 masterNormal_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 masterNormal_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 masterNormal_iam_a_slave = 0;

TIMER_HANDLE masterNormal_heartBeatTimers[1] = {TIMER_NONE};

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 masterNormal_obj1000 = 0x0;	/* 0 */
                    subindex masterNormal_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&masterNormal_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 masterNormal_obj1001 = 0x0;	/* 0 */
                    subindex masterNormal_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&masterNormal_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field. */
                    UNS8 masterNormal_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 masterNormal_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t masterNormal_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex masterNormal_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&masterNormal_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&masterNormal_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 masterNormal_obj1005 = 0x40000080;	/* 1073741952 */
                    ODCallback_t masterNormal_Index1005_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex masterNormal_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&masterNormal_obj1005 }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 masterNormal_obj1006 = 0x186A0;	/* 100000 */
                    ODCallback_t masterNormal_Index1006_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex masterNormal_Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&masterNormal_obj1006 }
                     };

/* index 0x1007 :   Synchronous Window Length. */
                    UNS32 masterNormal_obj1007 = 0x0;	/* 0 */
                    subindex masterNormal_Index1007[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&masterNormal_obj1007 }
                     };

/* index 0x1008 :   Manufacturer Device Name. */
                    UNS8 masterNormal_obj1008[10] = "";
                    subindex masterNormal_Index1008[] = 
                     {
                       { RO, visible_string, 10, (void*)&masterNormal_obj1008 }
                     };

/* index 0x1009 :   Manufacturer Hardware Version. */
                    UNS8 masterNormal_obj1009[10] = "";
                    subindex masterNormal_Index1009[] = 
                     {
                       { RO, visible_string, 10, (void*)&masterNormal_obj1009 }
                     };

/* index 0x100A :   Manufacturer Software Version. */
                    UNS8 masterNormal_obj100A[10] = "";
                    subindex masterNormal_Index100A[] = 
                     {
                       { RO, visible_string, 10, (void*)&masterNormal_obj100A }
                     };

/* index 0x100C :   Guard Time */ 
                    UNS16 masterNormal_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 masterNormal_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID. */
                    UNS32 masterNormal_obj1014 = 0x80;	/* 128 */
                    subindex masterNormal_Index1014[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&masterNormal_obj1014 }
                     };

/* index 0x1016 :   Consumer Heartbeat Time. */
                    UNS8 masterNormal_highestSubIndex_obj1016 = 1; /* number of subindex - 1*/
                    UNS32 masterNormal_obj1016[] = 
                    {
                      0x0	/* 0 */
                    };
                    subindex masterNormal_Index1016[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&masterNormal_highestSubIndex_obj1016 },
                       { RW, uint32, sizeof (UNS32), (void*)&masterNormal_obj1016[0] }
                     };

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 masterNormal_obj1017 = 0x3E8;	/* 1000 */
                    ODCallback_t masterNormal_Index1017_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex masterNormal_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&masterNormal_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 masterNormal_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 masterNormal_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 masterNormal_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 masterNormal_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 masterNormal_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex masterNormal_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&masterNormal_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&masterNormal_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&masterNormal_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&masterNormal_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&masterNormal_obj1018_Serial_Number }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 masterNormal_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 masterNormal_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x601;	/* 1537 */
                    UNS32 masterNormal_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x581;	/* 1409 */
                    UNS8 masterNormal_obj1280_Node_ID_of_the_SDO_Server = 0x1;	/* 1 */
                    subindex masterNormal_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&masterNormal_highestSubIndex_obj1280 },
                       { RW, uint32, sizeof (UNS32), (void*)&masterNormal_obj1280_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&masterNormal_obj1280_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&masterNormal_obj1280_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1281 :   Client SDO 2 Parameter. */
                    UNS8 masterNormal_highestSubIndex_obj1281 = 3; /* number of subindex - 1*/
                    UNS32 masterNormal_obj1281_COB_ID_Client_to_Server_Transmit_SDO = 0x601;	/* 1537 */
                    UNS32 masterNormal_obj1281_COB_ID_Server_to_Client_Receive_SDO = 0x582;	/* 1410 */
                    UNS8 masterNormal_obj1281_Node_ID_of_the_SDO_Server = 0x2;	/* 2 */
                    subindex masterNormal_Index1281[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&masterNormal_highestSubIndex_obj1281 },
                       { RW, uint32, sizeof (UNS32), (void*)&masterNormal_obj1281_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&masterNormal_obj1281_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&masterNormal_obj1281_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 masterNormal_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 masterNormal_obj1400_COB_ID_used_by_PDO = 0x181;	/* 385 */
                    UNS8 masterNormal_obj1400_Transmission_Type = 0x0;	/* 0 */
                    UNS16 masterNormal_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 masterNormal_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 masterNormal_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 masterNormal_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex masterNormal_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&masterNormal_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&masterNormal_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&masterNormal_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&masterNormal_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&masterNormal_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&masterNormal_obj1400_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&masterNormal_obj1400_SYNC_start_value }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 masterNormal_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 masterNormal_obj1401_COB_ID_used_by_PDO = 0x281;	/* 386 */
                    UNS8 masterNormal_obj1401_Transmission_Type = 0x0;	/* 0 */
                    UNS16 masterNormal_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 masterNormal_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 masterNormal_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 masterNormal_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex masterNormal_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&masterNormal_highestSubIndex_obj1401 },
                       { RW, uint32, sizeof (UNS32), (void*)&masterNormal_obj1401_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&masterNormal_obj1401_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&masterNormal_obj1401_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&masterNormal_obj1401_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&masterNormal_obj1401_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&masterNormal_obj1401_SYNC_start_value }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 masterNormal_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS32 masterNormal_obj1402_COB_ID_used_by_PDO = 0x381;	/* 387 */
                    UNS8 masterNormal_obj1402_Transmission_Type = 0x0;	/* 0 */
                    UNS16 masterNormal_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 masterNormal_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 masterNormal_obj1402_Event_Timer = 0x0;	/* 0 */
                    UNS8 masterNormal_obj1402_SYNC_start_value = 0x0;	/* 0 */
                    subindex masterNormal_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&masterNormal_highestSubIndex_obj1402 },
                       { RW, uint32, sizeof (UNS32), (void*)&masterNormal_obj1402_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&masterNormal_obj1402_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&masterNormal_obj1402_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&masterNormal_obj1402_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&masterNormal_obj1402_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&masterNormal_obj1402_SYNC_start_value }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 masterNormal_highestSubIndex_obj1600 = 1; /* number of subindex - 1*/
                    UNS32 masterNormal_obj1600[] = 
                    {
                      0x20000020	/* 536870944 */
                    };
                    subindex masterNormal_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&masterNormal_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&masterNormal_obj1600[0] }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 masterNormal_highestSubIndex_obj1601 = 3; /* number of subindex - 1*/
                    UNS32 masterNormal_obj1601[] = 
                    {
                      0x20010008,	/* 536936456 */
                      0x20020010,	/* 537002000 */
                      0x20030020	/* 537067552 */
                    };
                    subindex masterNormal_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&masterNormal_highestSubIndex_obj1601 },
                       { RW, uint32, sizeof (UNS32), (void*)&masterNormal_obj1601[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&masterNormal_obj1601[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&masterNormal_obj1601[2] }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 masterNormal_highestSubIndex_obj1602 = 1; /* number of subindex - 1*/
                    UNS32 masterNormal_obj1602[] = 
                    {
                      0x20040040	/* 537133120 */
                    };
                    subindex masterNormal_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&masterNormal_highestSubIndex_obj1602 },
                       { RW, uint32, sizeof (UNS32), (void*)&masterNormal_obj1602[0] }
                     };

/* index 0x2000 :   Mapped variable SlaveSysTick */
                    subindex masterNormal_Index2000[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&SlaveSysTick }
                     };

/* index 0x2001 :   Mapped variable g_nRfu8 */
                    subindex masterNormal_Index2001[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&g_nRfu8 }
                     };

/* index 0x2002 :   Mapped variable g_nRfu16 */
                    subindex masterNormal_Index2002[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&g_nRfu16 }
                     };

/* index 0x2003 :   Mapped variable g_nRfu32 */
                    subindex masterNormal_Index2003[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&g_nRfu32 }
                     };

/* index 0x2004 :   Mapped variable g_nRfu64 */
                    subindex masterNormal_Index2004[] = 
                     {
                       { RW, uint64, sizeof (UNS64), (void*)&g_nRfu64 }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable masterNormal_objdict[] = 
{
  { (subindex*)masterNormal_Index1000,sizeof(masterNormal_Index1000)/sizeof(masterNormal_Index1000[0]), 0x1000},
  { (subindex*)masterNormal_Index1001,sizeof(masterNormal_Index1001)/sizeof(masterNormal_Index1001[0]), 0x1001},
  { (subindex*)masterNormal_Index1003,sizeof(masterNormal_Index1003)/sizeof(masterNormal_Index1003[0]), 0x1003},
  { (subindex*)masterNormal_Index1005,sizeof(masterNormal_Index1005)/sizeof(masterNormal_Index1005[0]), 0x1005},
  { (subindex*)masterNormal_Index1006,sizeof(masterNormal_Index1006)/sizeof(masterNormal_Index1006[0]), 0x1006},
  { (subindex*)masterNormal_Index1007,sizeof(masterNormal_Index1007)/sizeof(masterNormal_Index1007[0]), 0x1007},
  { (subindex*)masterNormal_Index1008,sizeof(masterNormal_Index1008)/sizeof(masterNormal_Index1008[0]), 0x1008},
  { (subindex*)masterNormal_Index1009,sizeof(masterNormal_Index1009)/sizeof(masterNormal_Index1009[0]), 0x1009},
  { (subindex*)masterNormal_Index100A,sizeof(masterNormal_Index100A)/sizeof(masterNormal_Index100A[0]), 0x100A},
  { (subindex*)masterNormal_Index1014,sizeof(masterNormal_Index1014)/sizeof(masterNormal_Index1014[0]), 0x1014},
  { (subindex*)masterNormal_Index1016,sizeof(masterNormal_Index1016)/sizeof(masterNormal_Index1016[0]), 0x1016},
  { (subindex*)masterNormal_Index1017,sizeof(masterNormal_Index1017)/sizeof(masterNormal_Index1017[0]), 0x1017},
  { (subindex*)masterNormal_Index1018,sizeof(masterNormal_Index1018)/sizeof(masterNormal_Index1018[0]), 0x1018},
  { (subindex*)masterNormal_Index1280,sizeof(masterNormal_Index1280)/sizeof(masterNormal_Index1280[0]), 0x1280},
  { (subindex*)masterNormal_Index1281,sizeof(masterNormal_Index1281)/sizeof(masterNormal_Index1281[0]), 0x1281},
  { (subindex*)masterNormal_Index1400,sizeof(masterNormal_Index1400)/sizeof(masterNormal_Index1400[0]), 0x1400},
  { (subindex*)masterNormal_Index1401,sizeof(masterNormal_Index1401)/sizeof(masterNormal_Index1401[0]), 0x1401},
  { (subindex*)masterNormal_Index1402,sizeof(masterNormal_Index1402)/sizeof(masterNormal_Index1402[0]), 0x1402},
  { (subindex*)masterNormal_Index1600,sizeof(masterNormal_Index1600)/sizeof(masterNormal_Index1600[0]), 0x1600},
  { (subindex*)masterNormal_Index1601,sizeof(masterNormal_Index1601)/sizeof(masterNormal_Index1601[0]), 0x1601},
  { (subindex*)masterNormal_Index1602,sizeof(masterNormal_Index1602)/sizeof(masterNormal_Index1602[0]), 0x1602},
  { (subindex*)masterNormal_Index2000,sizeof(masterNormal_Index2000)/sizeof(masterNormal_Index2000[0]), 0x2000},
  { (subindex*)masterNormal_Index2001,sizeof(masterNormal_Index2001)/sizeof(masterNormal_Index2001[0]), 0x2001},
  { (subindex*)masterNormal_Index2002,sizeof(masterNormal_Index2002)/sizeof(masterNormal_Index2002[0]), 0x2002},
  { (subindex*)masterNormal_Index2003,sizeof(masterNormal_Index2003)/sizeof(masterNormal_Index2003[0]), 0x2003},
  { (subindex*)masterNormal_Index2004,sizeof(masterNormal_Index2004)/sizeof(masterNormal_Index2004[0]), 0x2004},
};

const indextable * masterNormal_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1003: i = 2;*callbacks = masterNormal_Index1003_callbacks; break;
		case 0x1005: i = 3;*callbacks = masterNormal_Index1005_callbacks; break;
		case 0x1006: i = 4;*callbacks = masterNormal_Index1006_callbacks; break;
		case 0x1007: i = 5;break;
		case 0x1008: i = 6;break;
		case 0x1009: i = 7;break;
		case 0x100A: i = 8;break;
		case 0x1014: i = 9;break;
		case 0x1016: i = 10;break;
		case 0x1017: i = 11;*callbacks = masterNormal_Index1017_callbacks; break;
		case 0x1018: i = 12;break;
		case 0x1280: i = 13;break;
		case 0x1281: i = 14;break;
		case 0x1400: i = 15;break;
		case 0x1401: i = 16;break;
		case 0x1402: i = 17;break;
		case 0x1600: i = 18;break;
		case 0x1601: i = 19;break;
		case 0x1602: i = 20;break;
		case 0x2000: i = 21;break;
		case 0x2001: i = 22;break;
		case 0x2002: i = 23;break;
		case 0x2003: i = 24;break;
		case 0x2004: i = 25;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &masterNormal_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status masterNormal_PDO_status[1] = {s_PDO_status_Initializer};

const quick_index masterNormal_firstIndex = {
  0, /* SDO_SVR */
  13, /* SDO_CLT */
  15, /* PDO_RCV */
  18, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const quick_index masterNormal_lastIndex = {
  0, /* SDO_SVR */
  14, /* SDO_CLT */
  17, /* PDO_RCV */
  20, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const UNS16 masterNormal_ObjdictSize = sizeof(masterNormal_objdict)/sizeof(masterNormal_objdict[0]); 

CO_Data masterNormal_Data = CANOPEN_NODE_DATA_INITIALIZER(masterNormal);

